### ISSUE TITLE
搜索栏的提示不能往下翻💥

### ISSUE THREAD

**Issue by maomihz** [Seancheey/RobocraftCalculator#2]
按方向键拖到底下就没法再看下面的啦。💥
![2016-04-26 18 04 35](https://cloud.githubusercontent.com/assets/3678366/14814551/5ce00848-0bd9-11e6-9d70-867e420ef66a.png)

你看这就坏掉了不能忍啊💥

**Comment by Seancheey** [comment]
不能忍啊！我用什么来改呢
